# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.6

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  typescript:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run TypeScript
          command: yarn tsc

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2 --ci

  prettier:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Prettier formatting check
          command: yarn prettier:check

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build package
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
      - typescript:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - prettier:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - typescript
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
